In [1]:
# Import dependencies
import pandas as pd

# Store file path
csv_path="Resources/Border_Crossing_Entry_Data.csv"

# Read the csv file
data_df = pd.read_csv(csv_path)
data_df

,Port Name,State,Port Code,Border,Date,Measure,Value,Location
0,Calexico East,California,2507,US-Mexico Border,03/01/2019 12:00:00 AM,Trucks,34447,POINT (-115.48433000000001 32.67524)
1,Van Buren,Maine,108,US-Canada Border,03/01/2019 12:00:00 AM,Rail Containers Full,428,POINT (-67.94271 47.16207)
2,Otay Mesa,California,2506,US-Mexico Border,03/01/2019 12:00:00 AM,Trucks,81217,POINT (-117.05333 32.57333)
3,Nogales,Arizona,2604,US-Mexico Border,03/01/2019 12:00:00 AM,Trains,62,POINT (-110.93361 31.340279999999996)
4,Trout River,New York,715,US-Canada Border,03/01/2019 12:00:00 AM,Personal Vehicle Passengers,16377,POINT (-73.44253 44.990010000000005)
...,...,...,...,...,...,...,...,...
346728,Norton,Vermont,211,US-Canada Border,01/01/1996 12:00:00 AM,Personal Vehicle Passengers,9119,POINT (-71.79 45.01)
346729,Columbus,New Mexico,2406,US-Mexico Border,01/01/1996 12:00:00 AM,Personal Vehicles,29486,POINT (-107.63 31.78)
346730,Hansboro,North Dakota,3415,US-Canada Border,01/01/1996 12:00:00 AM,Rail Containers Full,0,POINT (-99.35 49)
346731,Calexico East,California,2507,US-Mexico Border,01/01/1996 12:00:00 AM,Buses,0,POINT (-115.39 32.67)
346732,Presidio,Texas,2403,US-Mexico Border,01/01/1996 12:00:00 AM,Trucks,347,POINT (-104.39000000000001 29.56)

In [2]:
# List the colums in the dataset
data_df.columns

Index(['Port Name', 'State', 'Port Code', 'Border', 'Date', 'Measure', 'Value',
       'Location'],
      dtype='object')

In [3]:
# Reduce the dataset to the columns needed
reduced_df=data_df[['State', 'Border', 'Date', 'Measure', 'Value']]
reduced_df

,State,Border,Date,Measure,Value
0,California,US-Mexico Border,03/01/2019 12:00:00 AM,Trucks,34447
1,Maine,US-Canada Border,03/01/2019 12:00:00 AM,Rail Containers Full,428
2,California,US-Mexico Border,03/01/2019 12:00:00 AM,Trucks,81217
3,Arizona,US-Mexico Border,03/01/2019 12:00:00 AM,Trains,62
4,New York,US-Canada Border,03/01/2019 12:00:00 AM,Personal Vehicle Passengers,16377
...,...,...,...,...,...
346728,Vermont,US-Canada Border,01/01/1996 12:00:00 AM,Personal Vehicle Passengers,9119
346729,New Mexico,US-Mexico Border,01/01/1996 12:00:00 AM,Personal Vehicles,29486
346730,North Dakota,US-Canada Border,01/01/1996 12:00:00 AM,Rail Containers Full,0
346731,California,US-Mexico Border,01/01/1996 12:00:00 AM,Buses,0
346732,Texas,US-Mexico Border,01/01/1996 12:00:00 AM,Trucks,347

In [4]:
reduced_df.dtypes

State      object
Border     object
Date       object
Measure    object
Value       int64
dtype: object

In [5]:
# Split the Date column
reduced1_df = reduced_df.copy()
reduced1_df[['Jour', 'Time', 'AM/PM']] = reduced1_df['Date'].str.split(" ", expand = True)
reduced1_df

,State,Border,Date,Measure,Value,Jour,Time,AM/PM
0,California,US-Mexico Border,03/01/2019 12:00:00 AM,Trucks,34447,03/01/2019,12:00:00,AM
1,Maine,US-Canada Border,03/01/2019 12:00:00 AM,Rail Containers Full,428,03/01/2019,12:00:00,AM
2,California,US-Mexico Border,03/01/2019 12:00:00 AM,Trucks,81217,03/01/2019,12:00:00,AM
3,Arizona,US-Mexico Border,03/01/2019 12:00:00 AM,Trains,62,03/01/2019,12:00:00,AM
4,New York,US-Canada Border,03/01/2019 12:00:00 AM,Personal Vehicle Passengers,16377,03/01/2019,12:00:00,AM
...,...,...,...,...,...,...,...,...
346728,Vermont,US-Canada Border,01/01/1996 12:00:00 AM,Personal Vehicle Passengers,9119,01/01/1996,12:00:00,AM
346729,New Mexico,US-Mexico Border,01/01/1996 12:00:00 AM,Personal Vehicles,29486,01/01/1996,12:00:00,AM
346730,North Dakota,US-Canada Border,01/01/1996 12:00:00 AM,Rail Containers Full,0,01/01/1996,12:00:00,AM
346731,California,US-Mexico Border,01/01/1996 12:00:00 AM,Buses,0,01/01/1996,12:00:00,AM
346732,Texas,US-Mexico Border,01/01/1996 12:00:00 AM,Trucks,347,01/01/1996,12:00:00,AM

In [6]:
# Reduce the dataset to the columns needed
reduced2_df=reduced1_df[['State', 'Border', 'Measure', 'Value', 'Jour']]
reduced2_df

,State,Border,Measure,Value,Jour
0,California,US-Mexico Border,Trucks,34447,03/01/2019
1,Maine,US-Canada Border,Rail Containers Full,428,03/01/2019
2,California,US-Mexico Border,Trucks,81217,03/01/2019
3,Arizona,US-Mexico Border,Trains,62,03/01/2019
4,New York,US-Canada Border,Personal Vehicle Passengers,16377,03/01/2019
...,...,...,...,...,...
346728,Vermont,US-Canada Border,Personal Vehicle Passengers,9119,01/01/1996
346729,New Mexico,US-Mexico Border,Personal Vehicles,29486,01/01/1996
346730,North Dakota,US-Canada Border,Rail Containers Full,0,01/01/1996
346731,California,US-Mexico Border,Buses,0,01/01/1996
346732,Texas,US-Mexico Border,Trucks,347,01/01/1996

In [7]:
# Split the Jour column
reduced3_df = reduced2_df.copy()
reduced3_df[['Month', 'Day', 'Year']] = reduced3_df['Jour'].str.split("/", expand = True)
reduced3_df

,State,Border,Measure,Value,Jour,Month,Day,Year
0,California,US-Mexico Border,Trucks,34447,03/01/2019,03,01,2019
1,Maine,US-Canada Border,Rail Containers Full,428,03/01/2019,03,01,2019
2,California,US-Mexico Border,Trucks,81217,03/01/2019,03,01,2019
3,Arizona,US-Mexico Border,Trains,62,03/01/2019,03,01,2019
4,New York,US-Canada Border,Personal Vehicle Passengers,16377,03/01/2019,03,01,2019
...,...,...,...,...,...,...,...,...
346728,Vermont,US-Canada Border,Personal Vehicle Passengers,9119,01/01/1996,01,01,1996
346729,New Mexico,US-Mexico Border,Personal Vehicles,29486,01/01/1996,01,01,1996
346730,North Dakota,US-Canada Border,Rail Containers Full,0,01/01/1996,01,01,1996
346731,California,US-Mexico Border,Buses,0,01/01/1996,01,01,1996
346732,Texas,US-Mexico Border,Trucks,347,01/01/1996,01,01,1996

In [8]:
# Reduce the dataset to the columns needed
reduced3_df=reduced3_df[['State', 'Border', 'Measure', 'Value', 'Month', 'Year']]
reduced3_df

,State,Border,Measure,Value,Month,Year
0,California,US-Mexico Border,Trucks,34447,03,2019
1,Maine,US-Canada Border,Rail Containers Full,428,03,2019
2,California,US-Mexico Border,Trucks,81217,03,2019
3,Arizona,US-Mexico Border,Trains,62,03,2019
4,New York,US-Canada Border,Personal Vehicle Passengers,16377,03,2019
...,...,...,...,...,...,...
346728,Vermont,US-Canada Border,Personal Vehicle Passengers,9119,01,1996
346729,New Mexico,US-Mexico Border,Personal Vehicles,29486,01,1996
346730,North Dakota,US-Canada Border,Rail Containers Full,0,01,1996
346731,California,US-Mexico Border,Buses,0,01,1996
346732,Texas,US-Mexico Border,Trucks,347,01,1996

In [14]:
# years_to_analyze=['2010','2011','2012','2013','2014','2015','2016','2017','2018','2019']
# for year in years_to_analyze:
#     if reduced3_df['Year'] == year:



reduced4_df=reduced3_df.loc[reduced3_df["Year"] == '2010', reduced3_df["Year"] == '2011']
reduced4_df

IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).